services:
  smtk-app:
    build: .
    container_name: smtk_miner
    ports:
      - "8000:8000"
    volumes:
      # Data and Models live one level up from src to keep things tidy
      - ./data:/app/data
      - ./models:/app/models
    environment:
      # We point these to the absolute paths in the container
      - DATABASE_PATH=/app/data/decks.db
      - MODEL_DIR=/app/models
    restart: always